### ISSUE TITLE
Error on request payment from Zeus wallet

### ISSUE THREAD

**Issue by bota87** [lnbits/lndhub#5]
The payment was completed but I didn't get any confirm on Zeus (had to go to transaction history)

`2023-03-26 20:59:52.97 | INFO | 172.21.0.4:51270 - "GET /lndhub/ext/getbtc HTTP/1.0" 200
2023-03-26 21:00:17.85 | INFO | 172.21.0.4:51274 - "POST /lndhub/ext/addinvoice HTTP/1.0" 200
2023-03-26 21:00:18.05 | INFO | 172.21.0.4:51276 - "GET /lndhub/ext/getbtc HTTP/1.0" 200
2023-03-26 21:00:35.42 | INFO | > got a payment notification
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/lnbits/middleware.py", line 73, in __call__
    await self.app(scope, receive, send)
  File "/app/lnbits/middleware.py", line 52, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 182, in __call__
    await self.wait()
  File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 216, in wait
    await self._ping_task
  File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 259, in _ping
    await send({"type": "http.response.body", "body": ping, "more_body": True})
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 79, in sender
    await send(message)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 93, in send_with_gzip
    self.gzip_file.write(body)
  File "/usr/local/lib/python3.10/gzip.py", line 273, in write
    self._check_not_closed()
  File "/usr/local/lib/python3.10/_compression.py", line 14, in _check_not_closed
    raise ValueError("I/O operation on closed file")
ValueError: I/O operation on closed file
2023-03-26 21:00:47.22 | ERROR | Exception: I/O operation on closed file
2023-03-26 21:00:47.22 | ERROR | Exception in ASGI application

2023-03-26 21:01:01.66 | INFO | 172.21.0.4:51282 - "POST /lndhub/ext/auth?type=auth HTTP/1.0" 200
2023-03-26 21:01:01.71 | INFO | 172.21.0.4:51284 - "GET /lndhub/ext/balance HTTP/1.0" 200
2023-03-26 21:01:05.20 | INFO | 172.21.0.4:51286 - "GET /lndhub/ext/gettxs HTTP/1.0" 200`

**Comment by talvasconcelos** [comment]
I believe this could be a Zeus issue, probably! Just tested, and Zeus doesn't display the payment success! It shows up in transaction list.
