### ISSUE TITLE
gettxs error after admin top up

### ISSUE THREAD

**Issue by bota87** [lnbits/lndhub#6]
`2023-03-26 21:28:48.48 | INFO | 172.21.0.4:51584 - "GET /lndhub/ext/balance HTTP/1.0" 200
2023-03-26 21:28:49.80 | INFO | 172.21.0.4:51586 - "GET /lndhub/ext/gettxs HTTP/1.0" 200
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/lnbits/middleware.py", line 73, in __call__
    await self.app(scope, receive, send)
  File "/app/lnbits/middleware.py", line 52, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/lnbits/extensions/lndhub/views_api.py", line 181, in lndhub_getuserinvoices
    return [
  File "/app/lnbits/extensions/lndhub/views_api.py", line 183, in <listcomp>
    "r_hash": to_buffer(invoice.payment_hash),
  File "/app/lnbits/extensions/lndhub/utils.py", line 5, in to_buffer
    return {"type": "Buffer", "data": [b for b in bytes.fromhex(payment_hash)]}
ValueError: non-hexadecimal number found in fromhex() arg at position 2
2023-03-26 21:28:49.89 | ERROR | Exception: non-hexadecimal number found in fromhex() arg at position 2
2023-03-26 21:28:49.90 | INFO | 172.21.0.4:51588 - "GET /lndhub/ext/getuserinvoices HTTP/1.0" 500
2023-03-26 21:28:49.90 | ERROR | Exception in ASGI application

2023-03-26 21:28:57.09 | INFO | 172.21.0.4:51590 - "POST /lndhub/ext/auth?type=auth HTTP/1.0" 200
2023-03-26 21:28:57.21 | INFO | 172.21.0.4:51592 - "GET /lndhub/ext/balance HTTP/1.0" 200
`

**Comment by talvasconcelos** [comment]
Just tested it on bluewallet, and zeus, works fine! Can you check if issue still happens and close the issue if it's fixed?

**Comment by bota87** [comment]
It's not fixed on Zeus for me, still having the same error on lnbits logs, on Zeus on transaction history I can see spends but not top-up and received
![image](https://github.com/lnbits/lndhub/assets/52842374/207513b2-186d-4687-91e7-55505ad40168)
![image](https://github.com/lnbits/lndhub/assets/52842374/19eec7fb-7397-4b2e-9c48-32ab676db319)

**Comment by talvasconcelos** [comment]
This is my Zeus activity tab... the 10k sats was a top up

![zeus](https://imgur.com/rn8e34r.png)

**Comment by dni** [comment]
some of your payments still have an invalid payment_hash, that can come from topups that where made before we fixed them. try on a fresh wallet, if it works there it the old data and you will need to clean that invalid payment up.

**Comment by bota87** [comment]
Yeah probably that's the problem, if you don't plan to make a migration for old top up the issue can be closed for me
